import './globals.css';
import localFont from 'next/font/local';

const generalSans = localFont({
  src: '../fonts/GeneralSans-Variable.woff2',
  variable: '--font-general-sans',
  weight: '200 700',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={generalSans.variable}>
      <body>{children}</body>
    </html>
  );
}
